  - platform: wifi_signal
    id: "wifi_state"
    name: "WiFi Signal"
    update_interval: 60s
    icon: "mdi:signal-distance-variant"
    web_server:
      sorting_group_id: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    web_server:
      sorting_group_id: diagnostic
