substitutions:
  node_name: !secret device_6809_node_name
  ip_address: !secret device_6809_ip_address

packages:
  - !include ./_includes/common.yaml
  - !include ./_includes/wifi.yaml
  - !include ./_includes/wifi/villa_blackrock.yaml
  - !include ./_includes/binary_sensor.yaml
  - !include ./_includes/sensor.yaml
  - !include ./_includes/switch.yaml
  - !include ./_includes/text_sensor.yaml
  - !include ./_includes/time.yaml

esphome:
  comment: !secret device_6809_comment

esp32:
  board: esp32dev
  framework:
    type: esp-idf

switch:
  - platform: gpio
    name: "Relay switch"
    icon: "mdi:lightbulb_outline"
    pin: GPIO26
    id: relay_1
    restore_mode: RESTORE_DEFAULT_ON

#binary_sensor:
#  - platform: gpio
#    name: "Button"
#    pin:
#      number: GPIO27
#      mode:
#        input: true
#        pullup: true
#    id: button_kitchen
#    filters:
#      - invert:
#      - delayed_off: 50ms
#    on_press:
#      - switch.toggle: relay_1