---
platform: wifi_info
ip_address:
  id: "wifi_ip_address"
  name: "WiFi IP Address"
  web_server:
    sorting_group_id: diagnostic
ssid:
  id: "wifi_ssid"
  name: "WiFi SSID"
  web_server:
    sorting_group_id: diagnostic
bssid:
  id: "wifi_bssid"
  name: "WiFi BSSID"
  web_server:
    sorting_group_id: diagnostic
mac_address:
  id: "wifi_mac"
  name: "ESP Mac Wifi Address"
  web_server:
    sorting_group_id: diagnostic
scan_results:
  id: "wifi_scan_results"
  name: "ESP Latest Scan Results"
  web_server:
    sorting_group_id: diagnostic
dns_address:
  id: "wifi_dns_address"
  name: "ESP DNS Address"
  web_server:
    sorting_group_id: diagnostic
