---
wifi:
  ap:
    ssid: ${node_name}
    password: !secret ap_wifi_password
  domain: ""
  use_address: ${ip_address}
  fast_connect: true # чтобы подключаться к скрытой сети, отключает предварительное сканирование
  reboot_timeout: 0s
  min_auth_mode: WPA2

captive_portal:

sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    name: WiFi Signal
    update_interval: 60s
    icon: mdi:signal-distance-variant
    web_server:
      sorting_group_id: diagnostic

  - platform: copy
    id: wifi_signal_percent
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    filters: 
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: Signal %
    entity_category: diagnostic
    device_class: ''
    web_server:
      sorting_group_id: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      id: "wifi_ip_address"
      name: "WiFi IP Address"
      web_server:
        sorting_group_id: diagnostic
    ssid:
      id: "wifi_ssid"
      name: "WiFi SSID"
      web_server:
        sorting_group_id: diagnostic
    bssid:
      id: "wifi_bssid"
      name: "WiFi BSSID"
      web_server:
        sorting_group_id: diagnostic
    mac_address:
      id: "wifi_mac"
      name: "ESP Mac Wifi Address"
      web_server:
        sorting_group_id: diagnostic
    scan_results:
      id: "wifi_scan_results"
      name: "ESP Latest Scan Results"
      web_server:
        sorting_group_id: diagnostic
    dns_address:
      id: "wifi_dns_address"
      name: "ESP DNS Address"
      web_server:
        sorting_group_id: diagnostic
